### Buscar produto por nome
GET http://localhost:3000/getPessoa

### Cadastrar produto
POST http://localhost:3000/newPessoa
Content-Type: application/json

{
    "nome": "Samuel",
    "idade": 20,
    "cep": "81825255"
}